name: build, release and publish

on:
  push:
    tags:
      "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
          - x64
        os:
          - macos-latest
          - ubuntu-24.04
          - windows-latest
        include:
          - arch: arm64
            os: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm run prebuild
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: prebuilds
          retention-days: 1

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write # Needed for softprops/action-gh-release.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          path: prebuilds
          merge-multiple: true
      - run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
        id: get_version
      - run:
          tar -zcvf "${{ steps.get_version.outputs.version }}-darwin-x64.tar.gz" -C "prebuilds" darwin-x64
      - run:
          tar -zcvf "${{ steps.get_version.outputs.version }}-linux-x64.tar.gz" -C "prebuilds" linux-x64
      - run:
          tar -zcvf "${{ steps.get_version.outputs.version }}-win32-x64.tar.gz" -C "prebuilds" win32-x64
      - run:
          tar -zcvf "${{ steps.get_version.outputs.version }}-linux-arm64.tar.gz" -C "prebuilds" linux-arm64
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.get_version.outputs.version }}-*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          path: prebuilds
          merge-multiple: true
      - name: Publish
        run: |
          npm config set provenance true
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
