name: CI

on:
  push:
    tags:
      "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
          - x64
        os:
          - macos-latest
          - ubuntu-24.04
          - windows-latest
        include:
          - arch: arm64
            os: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: npm install

      - name: Build binaries
        run: npm run prebuild

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: prebuilds
          retention-days: 1

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          path: prebuilds
          merge-multiple: true
          
      - name: Publish
        run: |
          npm config set provenance true
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
